spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/restaurantreservation?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: restaurantreservation
    password: restaurantreservation

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  jwt:
    secret: restaurant-reservation-secret-key-sample

service:
  version: v1
  api:
    prefix: /api/${service.version}
    user:
      prefix: /users
      check-id: /sign-up/check-id
      check-nickname: /sign-up/check-nickname
      sign-up: /sign-up
      login: /login
      register-partner: ${service.api.user.prefix}/partner
    restaurant:
      prefix: /restaurants
      save: ${service.api.restaurant.prefix}
      search-auto: ${service.api.restaurant.prefix}/search/autocomplete
      search: ${service.api.restaurant.prefix}/search
