spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;
#    username: sa
#    password:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/restaurantreservation?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: restaurantreservation
    password: restaurantreservation

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # -> 대.소문자를 구분하게끔 해주는 정책.
    show-sql: true
    defer-datasource-initialization: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  config:
    import: secret.yml

service:
  version: v1
  api:
    prefix: /api/${service.version}
    user:
      check-id: /sign-up/check-id
      check-nickname: /sign-up/check-nickname
      sign-up: /sign-up
      login: /login
      refresh: /login/refresh
      update-pw: /users/password
      find-profile: /users/profile
      update-profile: /users/profile
      register-partner: /users/partner
      resign: /users/resign

    restaurant:
      save: /restaurants
      update: /restaurants/{restaurantId}
      delete: /restaurants/{restaurantId}
      request-delete: /restaurants/{restaurantId}/request
      search-auto: /restaurants/search/autocomplete
      search-name: /restaurants/search/name
      search-address: /restaurants/search/address
      find: /restaurants/{restaurantId}

    menu:
      add: /restaurants/{restaurantId}/menus
      update: /restaurants/{restaurantId}/menus/{menuId}
      remove: /restaurants/{restaurantId}/menus/{menuId}

    reservation:
      reserve: /reservations
      cancel: /reservations/{reservationId}/cancel
      approve: /reservations/{reservationId}/approve
      refuse: /reservations/{reservationId}/refuse
      visit: /reservations/{reservationId}/visit
      find-list-client: /reservations/client
      find-list-manager: /reservations/manager
      find: /reservations/{reservationId}

    review:
      save: /restaurants/{restaurantId}/reviews
      update: /restaurants/{restaurantId}/reviews/{reviewId}
      delete: /restaurants/{restaurantId}/reviews/{reviewId}
