spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  jwt:
    secret: restaurant-reservation-secret-key-sample

service:
  version: v1
  api:
    prefix: /api/${service.version}
    user:
      check-id: /sign-up/check-id
      check-nickname: /sign-up/check-nickname
      sign-up: /sign-up
      login: /login
      register-partner: /user/partner